import '../styles/globals.css';
import type { Metadata } from "next";
import Script from "next/script";
import "/public/assets/themify-icons/themify-icons.css";
import "/public/assets/responsive.css"
import Header from '../components/Header';
import Footer from '../components/Footer';

export const metadata: Metadata = {
  title: "App E-commerce",
  description: "Generated by create next app",
};

// Định nghĩa interface trước khi sử dụng
interface RootLayoutProps {
  children: React.ReactNode; // Chỉ định kiểu cho children
}
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
        />
      </head>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
        <Script src="https://code.jquery.com/jquery-3.6.0.min.js" />
        <Script src="/assets/home.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}